BRONZE:
  prefix_with_environment: true
  description: "Raw data landing zone"
  schemas:
    source_systems:
      - SALESFORCE
      - STRIPE
      - HUBSPOT
      - ZENDESK
    monitoring:
      - FIVETRAN_LOG
      - STITCH_LOG
      - AIRBYTE_LOG
SILVER:
  prefix_with_environment: true
  description: "Standardized data"
  schemas:
    entities:
      - CUSTOMERS
      - ORDERS
      - PRODUCTS
      - EMPLOYEES
    domains:
      - SALES
      - MARKETING
      - SUPPORT

GOLD:
  prefix_with_environment: true
  description: "Business-ready data"
  schemas:
    domains:
      - FINANCE
      - SALES
      - MARKETING
      - OPERATIONS
    reporting:
      - ANALYTICS
      - REPORTING
      - DASHBOARDS

PLATINUM:
  prefix_with_environment: true
  description: "Feature store and ML artifacts"
  schemas:
    infrastructure:
      - FEATURE_STORE
      - MODEL_REGISTRY
      - MODEL_METRICS
    domains:
      - CUSTOMER_FEATURES
      - PRODUCT_FEATURES
      - FORECASTING