services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/foundation:cached
      - ~/.aws:/home/vscode/.aws:cached
      - ~/.zshrc:/home/vscode/.zshrc:cached
    command: sleep infinity

volumes:
  devcontainer_volume:
