secrets:
  snowflake_service_account:
    name: "SnowflakeCredentials"  # Name in Secrets Manager
    description: "Credentials for Snowflake service account"
    template:
      username: "svc_aws_integration"
      account: ""
      warehouse: ""
      database: ""
      schema: ""
    rotation:
      enabled: true
      interval_days: 30
    password_options:
      length: 16
      exclude_chars: '@"\\'
      exclude_punctuation: true
      include_space: false

  # Example of another secret
  # redshift_credentials:
  #   name: "RedshiftCredentials"
  #   description: "Credentials for Redshift connection"
  #   template:
  #     username: "svc_redshift"
  #     host: ""
  #     port: "5439"
  #     database: ""
  #   rotation:
  #     enabled: true
  #     interval_days: 90 