templates:
  snowflake:
    type: "snowflake"
    rotation_days: 90
    password_options:
      password_length: 32
      exclude_characters: '"@/\\'
      exclude_punctuation: true
      require_each_included_type: true
    template:
      account: ""
      user: ""
      password: ""

secrets:
  svc-hoid:
    template: "snowflake"
    description: "Snowflake service account for administrative operations"
    template_overrides:
      user: "SVC_HOID"
    password_options:
      password_length: 64
      exclude_characters: '"@/\\$'