warehouses:
  COSMERE:
    sizes: [ALL]
roles:
  HOID:
    description: "Administrative role for platform automation"
    grants_to: [SYSADMIN, SECURITYADMIN]
service_users:
  SVC_HOID:
    prefix_with_environment: false
databases:
  COSMERE:
    prefix_with_environment: false
    description: "Administrative database for platform management"
    schemas:
      - ADMIN
      - AUDIT
      - SECURITY
