# Core database structure and schemas
databases:
  BRONZE:
    description: "Raw data landing zone"
    schemas:
      # Source system schemas
      - SALESFORCE
      - STRIPE
      - HUBSPOT
      - ZENDESK
      # Monitoring/logging schemas
      - FIVETRAN_LOG
      - STITCH_LOG
      - AIRBYTE_LOG
      
  SILVER:
    description: "Standardized data"
    schemas:
      # Core business entities
      - CUSTOMERS
      - ORDERS
      - PRODUCTS
      - EMPLOYEES
      # Standardized source data
      - SALES
      - MARKETING
      - SUPPORT
      
  GOLD:
    description: "Business-ready data"
    schemas:
      # Business domains
      - FINANCE
      - SALES
      - MARKETING
      - OPERATIONS
      # Reporting
      - ANALYTICS
      - REPORTING
      - DASHBOARDS
      
  PLATINUM:
    description: "Feature store and ML artifacts"
    schemas:
      # ML infrastructure
      - FEATURE_STORE
      - MODEL_REGISTRY
      - MODEL_METRICS
      # ML domains
      - CUSTOMER_FEATURES
      - PRODUCT_FEATURES
      - FORECASTING
