# Core access role definitions and permissions
access_roles:
  OWNER:
    description: "Full control of database objects"
    permissions:
      - OWNERSHIP
      - MODIFY
      - MONITOR
      - USAGE
      - CREATE SCHEMA
      - CREATE TABLE
      - CREATE VIEW
      - CREATE STAGE
      - CREATE PIPE
      
  RW:
    description: "Read and write access to database objects"
    permissions:
      - USAGE
      - SELECT
      - INSERT
      - UPDATE
      - DELETE
      - CREATE TABLE
      - CREATE VIEW
      - CREATE STAGE
      
  RO:
    description: "Read-only access to database objects"
    permissions:
      - USAGE
      - SELECT

# Functional role definitions and their access patterns
functional_roles:
  ML_ENGINEER:
    description: "Machine Learning Engineer access pattern"
    access_roles:
      BRONZE:
        - schemas: [SALESFORCE, STRIPE, HUBSPOT]
          level: RO
      SILVER:
        - schemas: [CUSTOMERS, PRODUCTS]
          level: RW
      GOLD:
        - schemas: [ANALYTICS, REPORTING]
          level: RO
      PLATINUM:
        - schemas: [FEATURE_STORE, MODEL_REGISTRY, MODEL_METRICS]
          level: RW
        - schemas: [CUSTOMER_FEATURES, PRODUCT_FEATURES]
          level: RW

  DATA_ENGINEER:
    description: "Data Engineer access pattern"
    access_roles:
      BRONZE:
        - schemas: [ALL]
          level: RW
      SILVER:
        - schemas: [ALL]
          level: RW
      GOLD:
        - schemas: [ALL]
          level: RW
      PLATINUM:
        - schemas: [FEATURE_STORE]
          level: RO

  DATA_ANALYST:
    description: "Data Analyst access pattern"
    access_roles:
      SILVER:
        - schemas: [ALL]
          level: RO
      GOLD:
        - schemas: [ALL]
          level: RO
      PLATINUM:
        - schemas: [FEATURE_STORE]
          level: RO

  APPLICATION_ENGINEER:
    description: "Application Engineer access pattern"
    access_roles:
      GOLD:
        - schemas: [ANALYTICS, REPORTING]
          level: RO
      PLATINUM:
        - schemas: [FEATURE_STORE]
          level: RO

# Service role definitions and their access patterns
service_roles:
  SVC_AIRFLOW:
    description: "Airflow orchestration service account"
    access_roles:
      BRONZE: RW
      SILVER: RW
      GOLD: RW
    warehouses:
      - LOAD_WH
    
  SVC_FIVETRAN:
    description: "Fivetran EL service account"
    access_roles:
      BRONZE: RW
    warehouses:
      - LOAD_WH

  SVC_HOID:
    description: "Administrative automation service account"
    special_role: HOID  # Indicates this service account gets HOID role 