# Default warehouse settings
defaults:
  auto_suspend: 60
  auto_resume: true
  initially_suspended: true
  min_cluster_count: 1
  max_cluster_count: 1
  scaling_policy: STANDARD

# Available sizes
sizes:
  - XSMALL
  - SMALL
  - MEDIUM
  - LARGE
  - XLARGE

# Warehouse definitions with optional overrides
warehouses:
  BRONZE:
    description: "Raw data loading and processing"
    sizes:
      - SMALL
      - MEDIUM
    overrides:
      auto_suspend: 300
      min_cluster_count: 1
      max_cluster_count: 3
      scaling_policy: ECONOMY

  SILVER:
    description: "Data transformation and modeling"
    sizes:
      - SMALL
      - MEDIUM
      - LARGE

  GOLD:
    description: "Business analytics and reporting"
    sizes:
      - XSMALL
      - SMALL
    overrides:
      auto_suspend: 120

  PLATINUM:
    description: "ML training and inference"
    sizes:
      - MEDIUM
      - LARGE
    overrides:
      auto_suspend: 600
      min_cluster_count: 1
      max_cluster_count: 4
      scaling_policy: ECONOMY