services:
  localstack:
    container_name: "localstack-snowflake"
    image: localstack/snowflake
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:443:443"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DEBUG=1
    volumes:
      - "./volume:/var/lib/localstack"
    networks:
      devcontainer_network:
        aliases:
          - localstack
          - snowflake.localhost.localstack.cloud

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/foundation:cached
      - ~/.aws:/home/vscode/.aws:cached
      - ~/.zshrc:/home/vscode/.zshrc:cached
    command: sleep infinity
    networks:
      - devcontainer_network

networks:
  devcontainer_network:
    name: devcontainer_network

volumes:
  devcontainer_volume:
